website/models.py
from . import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

class Game(db.Model):
    name = db.Column(db.String(100), primary_key=True)
    password = db.Column(db.String(100))
    white = db.Column(db.String)
    black = db.Column(db.String)
    fen = db.Column(db.String)
    result = db.Column(db.String)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from os import path

db = SQLAlchemy()
DB_NAME = 'database.db'

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = 'asekljhgfaowibnrve'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Game

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('instance/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Database created!')

website/auth.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from . import db

auth = Blueprint('auth', __name__)

@auth.route('login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                login_user(user, remember=True)
                flash('Logged in successfully', category='success')
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password', category='error')
        else:
            flash('User not found', category='error')
    return render_template('login.html', user=current_user)

@auth.route('sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user1 = User.query.filter_by(email=email).first()
        user2 = User.query.filter_by(username=username).first()

        if user1:
            flash('Email already in use', category='error')
        elif user2:
            flash('Username already taken', category='error')
        elif len(username) < 4:
            flash('Username must be at least 4 characters', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters', category='error')
        else:
            new_user = User(email=email, username=username, password=password1)
            db.session.add(new_user)
            db.session.commit()

            flash('Account created successfully', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))
    return render_template('sign_up.html', user=current_user)

@auth.route('logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

website/views.py
from flask import Blueprint, render_template, send_from_directory, redirect, url_for, flash, request
from flask_login import current_user
import os

from .models import Game
from . import db

DEFAULT_FEN = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('home.html', user=current_user, online=True)

@views.route('/create_game', methods=['POST'])
def create_game():
    game = Game.query.filter_by(name=request.form['name']).first()

    if game:
        flash('Room already exists', category='error')
        return "Room already exists", 400
    else:
        new_game = Game(name=request.form['name'], password=request.form['password'], fen=DEFAULT_FEN)
        db.session.add(new_game)
        db.session.commit()

        return 'test'
    
@views.route('/join_game', methods=['POST'])
def join_game():
    game = Game.query.filter_by(name=request.form['name']).first()
    locked = True

    print(request.form['password'], game.password)

    if not game:
        flash('Room not found', category='error')
        return "Room not found", 400
    
    if game.password == request.form['password']:
        locked = False

    elif request.form['spectate'] == 'false':
        flash ('Incorrect password', category='error')
        return "Incorrect password", 400
    print('join ', locked)
    return str(locked)

@views.route('/game/<id>')
def game_room(id):
    locked = True
    passed = request.args.get('locked')
    if passed:
        locked = passed
    print('game ', locked)
    return render_template('game.html', user=current_user, online=True, id=id, locked=locked)

@views.route('/pieces/<piece>')
def get_piece_image(piece):
    path = os.path.join(os.path.dirname(os.getcwd()), 'online-chess', 'website', 'static', 'images', 'pieces')
    return send_from_directory(path, piece.replace('-', '_') + '.png')

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta id="jinjaData" data-user="{{ user }}">
  {% block metas %}{% endblock %}
  <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../static/styles/styles.css">
  {% block links %}
  <link rel="stylesheet" href="../static/styles/base.css">
  {% endblock %}
  <title>{% block title %}Home{% endblock %}</title>
</head>
<body class="m-0 bg-slate-100">
  <header class="w-full bg-zinc-500 flex justify-between h-14 py-1 px-6">
    <div class="flex justify-between items-center h-full text-xl my-0 mx-1" id="left">
      <a class="text-white no-underline my-0 mx-3 hover:text-gray-200" href="{{ url_for('views.home') }}">Chess.org</a>
      <a class="text-white no-underline my-0 mx-3 hover:text-gray-200" href="">Active Games</a>
    </div>
    <div class="flex justify-between items-center h-full text-xl my-0 ml-1 mr-3" id="right">
      {% if user.is_authenticated %}
      <a class="text-white no-underline my-0 mx-3 hover:text-gray-200" href="{{ url_for('auth.logout') }}">Logout</a>
      <a class="text-white no-underline my-0 mx-3 hover:text-gray-200" href="">{{ user.username }}</a>
      {% else %}
      <a class="text-white no-underline my-0 mx-3 hover:text-gray-200" href="{{ url_for('auth.login') }}">Login</a>
      <a class="text-white no-underline my-0 mx-3 hover:text-gray-200" href="{{ url_for('auth.sign_up') }}">Sign up</a>
      {% endif %}
    </div>
  </header>
  {% with messages = get_flashed_messages(with_categories=true) %} 
  {% if messages %} 
    {% for category, message in messages %} 
      {% if category ==  'error' %}
        <div class="alert alert-danger alert-dismissable fade show absolute" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissable fade show absolute" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
  {% endif %} {% endfor %} {% endif %} {% endwith %}
  {% block content %}{% endblock %}
  <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  {% block baseScripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="../static/javascript/home.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
  <script src="../static/javascript/conversion.js"></script>
  <script src="../static/javascript/pieces.js"></script>
  <script src="../static/javascript/chess.js"></script>
  {% endblock %}
  {% block extrasScripts %}{% endblock %}
</body>
</html>

website/templates/game.html
{% extends "base.html" %}
{% block title %}Chess.org{% endblock %}
{% block metas %}
  <meta id="online" data-online="True" data-locked="{{ locked }}">
{% endblock %}
{% block links %}
<link rel="stylesheet" href="../static/styles/base.css">
<link rel="stylesheet" href="../static/styles/home.css">
{% endblock %}
{% block content %}
<div class="home-content">
  <div class="w-[20%] h-[60vh] bg-zinc-500 rounded-md shadow">
    <div class="h-[95%]"></div>
    <input type="text" class="min-h-5 w-full h-[5%] border-none p-0 pl-1 rounded" placeholder="Start typing..." id="chat-input">
  </div>
  <div class="w-[min(80vh,_75vw)] aspect-square grid grid-rows-8 grid-cols-8 bg-[rgba(69,_102,_186,_0.8)]" id="board"></div>
  <div class="info-box">
    
  </div>
</div>
<div class="play-as">
  <button id="playing-as-white" data-color="white" onclick="playAs(this.dataset.color)">Play as White</button>
  <button id="playing-as-black" data-color="black" onclick="playAs(this.dataset.color)">Play as Black</button>
</div>
{% endblock %}
{% block extrasScripts %}
<script src="../static/javascript/online.js"></script>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Chess.org{% endblock %}
{% block links %}
<link rel="stylesheet" href="../static/styles/base.css">
<link rel="stylesheet" href="../static/styles/home.css">
{% endblock %}
{% block content %}
<div class="hidden absolute z-50 w-full h-[calc(100%_-_50px)] bg-[rgba(0,_0,_0,_0.4)]" id="create-popup">
  <div class="popup block bg-gray-100 absolute z-[60] top-1/2 left-1/2 -translate-x-1/2 translate-y-[calc(-50%_-_25px)] py-4 px-7 rounded-xl w-[380px]">
    <div class="absolute top-[5px] right-[15px] h-[15px] cursor-pointer text-2xl" onclick="document.querySelector('#create-popup').style['display'] = 'none'">&times;</div>
    <h2 class="text-center text-[1.8em] mb-2">Create Room</h2>
    <form id="create-room">
      <label class="text[1.2em]" for="create-name">Name</label>
      <input type="text" class="enter-submit block w-full p-2 mb-[10px] outline-none rounded border-[1.5px] border-gray-400" name="name" id="create-name" placeholder="Enter room name ...">
      <label class="text[1.2em]" for="create-password">Password</label>
      <input type="password" class="enter-submit block w-full p-2 mb-[10px] outline-none rounded border-[1.5px] border-gray-400" name="password" id="create-password" placeholder="Enter room password ...">
      <button type="button" class="w-full h-10 border-none outline-none rounded text-gray-100 mt-2 bg-[hsl(0,_0%,_10%)] hover:bg-[hsl(0,_0%,_15%)] active:bg-[hsl(0,_0%,_20%)]" onclick="createRoom(this.parentElement)">Create</button>
    </form>
  </div>
</div>
<div class="hidden absolute z-50 w-full h-[calc(100%_-_50px)] bg-[rgba(0,_0,_0,_0.4)]" id="join-popup">
  <div class="popup block bg-gray-100 absolute z-[60] top-1/2 left-1/2 -translate-x-1/2 translate-y-[calc(-50%_-_25px)] py-4 px-7 rounded-xl w-[380px]">
    <div class="absolute top-[5px] right-[15px] h-[15px] cursor-pointer text-2xl" onclick="document.querySelector('#join-popup').style['display'] = 'none'">&times;</div>
    <h2 class="text-center text-[1.8em] mb-2">Join Room</h2>
    <form id="join-room">
      <label class="text[1.2em]" for="join-name">Name</label>
      <input type="text" class="enter-submit block w-full p-2 mb-[10px] outline-none rounded border-[1.5px] border-gray-400" name="name" id="join-name" placeholder="Enter room name ...">
      <label class="text[1.2em]" for="join-password">Password</label>
      <input type="password" class="enter-submit block w-full p-2 mb-[10px] outline-none rounded border-[1.5px] border-gray-400" name="password" id="join-password" placeholder="Enter room password ...">
      <input type="checkbox" class="relative top-[2px] w-4 aspect-square mr-1 mt-1" name="spectate" id="join-spectate">
      <label class="text[1.2em]" for="join-spectate">Or just spectate</label>
      <button type="button" class="w-full h-10 border-none outline-none rounded text-gray-100 mt-2 bg-[hsl(0,_0%,_10%)] hover:bg-[hsl(0,_0%,_15%)] active:bg-[hsl(0,_0%,_20%)]" onclick="joinRoom(this.parentElement)">Join</button>
    </form>
  </div>
</div>

<div class="flex justify-around items-center my-7 mx-12">
  <div class="w-[20%] h-[60vh] bg-zinc-500 rounded-md shadow">
    <div class="h-[95%]"></div>
    <input type="text" class="min-h-5 w-full h-[5%] border-none p-0 pl-1 rounded" placeholder="Start typing..." id="chat-input">
  </div>
  <div id="board" class="w-[min(80vh,_75vw)] aspect-square grid grid-rows-8 grid-cols-8 bg-[rgba(69,_102,_186,_0.8)] shadow-md"></div>
  <div class="flex flex-col content-between w-[20%]">
    <button class="h-10 bg-zinc-500 hover:bg-zinc-400 active:bg-zinc-300 text-lg text-black border-none rounded p-1 my-2 mx-0" id="challenge">Challenge a Friend</button>
    <button class="h-10 bg-zinc-500 hover:bg-zinc-400 active:bg-zinc-300 text-lg text-black border-none rounded p-1 my-2 mx-0" id="join-room" onclick="document.querySelector('#join-popup').style['display'] = 'initial'">Join Room</button>
    <button class="h-10 bg-zinc-500 hover:bg-zinc-400 active:bg-zinc-300 text-lg text-black border-none rounded p-1 my-2 mx-0" id="create-room" onclick="document.querySelector('#create-popup').style['display'] = 'initial'">Create Room</button>
  </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block links %}
<link rel="stylesheet" href="../static/styles/base.css">
<link rel="stylesheet" href="../static/styles/auth.css">
{% endblock %}
{% block content %}
<div class="w-full h-[calc(100vh_-_56px)] bg-[hsl(0,_0%,_70%)]">
  <div class="block bg-gray-100 absolute top-1/2 left-1/2 -translate-x-1/2 translate-y-[calc(-50%_-_25px)] pt-4 pb-8 px-7 w-[500px] rounded-[10px]">
    <h2 class="text-center text-[1.8em] mb-[10px]">Login</h2>
    <form method="POST">
      <fieldset>
        <label class="text-[1.2em]" for="user">E-mail:</label>
        <input id="email" name="email" type="email" class="email block w-full p-[10px] mb-[10px] outline-none border-[1.5px] border-gray-400 rounded" placeholder="Enter Email ..." required>
        <label class="text-[1.2em]" for="password">Password:</label>
        <input id="password" name="password" type="password" class="block w-full p-[10px] mb-[10px] outline-none border-[1.5px] border-gray-400 rounded" placeholder="Enter Password ..." required>
        <button type="submit" class="submit w-full h-10 border-none outline-none rounded mt-2 text-gray-100 bg-[hsl(0,_0%,_10%)] hover:bg-[hsl(0,_0%,_15%)] active:bg-[hsl(0,_0%,_20%)]">Login</button>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign up{% endblock %}
{% block links %}
<link rel="stylesheet" href="../static/styles/base.css">
<link rel="stylesheet" href="../static/styles/auth.css">
{% endblock %}
{% block content %}
  <div class="w-full h-[calc(100vh_-_56px)] bg-[hsl(0,_0%,_70%)]">
  <div class="block bg-gray-100 absolute top-1/2 left-1/2 -translate-x-1/2 translate-y-[calc(-50%_-_25px)] pt-4 pb-8 px-7 w-[500px] rounded-[10px]">
    <h2 class="text-center text-[1.8em] mb-[10px]">Sign Up</h2>
    <form method="POST">
      <fieldset>
        <label class="text-[1.2em]" for="email">E-mail:</label>
        <input id="email" name="email" type="email" class="email block w-full p-[10px] mb-[10px] outline-none border-[1.5px] border-gray-400 rounded" placeholder="Enter Email ..." required>
        <label class="text-[1.2em]" for="username">Username:</label>
        <input id="username" name="username" type="text" class="username block w-full p-[10px] mb-[10px] outline-none border-[1.5px] border-gray-400 rounded" placeholder="Enter Username ..." required>
        <label class="text-[1.2em]" for="password1">Password:</label>
        <input id="password1" name="password1" type="password" class="block w-full p-[10px] mb-[10px] outline-none border-[1.5px] border-gray-400 rounded" placeholder="Enter Password ..." required>
        <label class="text-[1.2em]" for="password2">Confirm Password:</label>
        <input id="password2" name="password2" type="password" class="block w-full p-[10px] mb-[10px] outline-none border-[1.5px] border-gray-400 rounded" placeholder="Confirm Password ..." required>
        <button type="submit" class="submit w-full h-10 border-none outline-none rounded mt-2 text-gray-100 bg-[hsl(0,_0%,_10%)] hover:bg-[hsl(0,_0%,_15%)] active:bg-[hsl(0,_0%,_20%)]">Login</button>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}